# SPDX-FileCopyrightText: Copyright (c) 2021 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/latex
install: |-
  sudo "$(pwd)/lecture-notes/tlmgr-install.sh"
merge:
  script: |-
    make
